# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Kiowa spellchecker"
kio = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Kiowa, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
kio = "TRANSLATE: A spellchecker for Kiowa, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.kio"

[windows]
system_product_code = "{13A6285A-81C1-4920-8502-29D45A14E623}_is1"
legacy_product_codes = [
    { value = "B177730B-D332-45D9-A2BD-ED7AFB551D5A", kind = "nsis" },
    { value = "84AAC359-AF47-4E32-AA1A-22B61B54CDF4", kind = "nsis" }
]
extra_locales = { kio-US = "kio" }

[package.speller]
name = "Kiowa"
version = "0.1.1"

[package.grammar]
name = "Kiowa"
version = "0.1.0"

[package.tts-textproc]
name = "Kiowa"
version = "0.1.0"

[package.hyphenator]
name = "Kiowa"
version = "0.1.0"
