template = "https://github.com/giellalt/template-lang-und"
rev_id = 262
template_sha = "e76bfc45ca43118d648ca429564512658ac2ea78"

[replacements]
__GLOTTOLOG_ID__ = "kiow1266"
__REPO__ = "lang-kio"
__UND2C__ = "kio"
__UNDEFINED__ = "Kiowa"
__UND__ = "kio"
