template = "https://github.com/giellalt/template-lang-und"
rev_id = 275
template_sha = "ae7f0a90eca4365746c3ec57f8e39437abd6d807"

[replacements]
__GLOTTOLOG_ID__ = "kiow1266"
__REPO__ = "lang-kio"
__UND2C__ = "kio"
__UNDEFINED__ = "Kiowa"
__UND__ = "kio"
